---
engines:
  phpcodesniffer:
    enabled: true
    config: 
      file_extensions: "php"
      standard: "ruleset.xml"
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      UnusedFormalParameter:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.module"
  - "**.php"
exclude_paths: []